name: Deploy the application to Google Cloud Run
on:
 push:
   branches: [ master ]
jobs:
 setup-build-publish-deploy:
   name: Setup, Build, Publish, and Deploy
   runs-on: ubuntu-latest
   steps:
   - name: Checkout
     uses: actions/checkout@v2

   - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
     with:
       service_account_key: ${{ secrets.GCLOUD_AUTH }}
       run: |
          echo Hello there!
   # Configure docker to use the gcloud command-line tool as a credential helper
   - name: Setup
     run: |
        gcloud auth configure-docker

   # Build the Docker image
   - name: Build
     run: |
        docker build --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_NAME }}:$(cat VERSION) .

     #Push the Docker image to Google Container Registry
   - name: Publish
     run: |
        docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_NAME }}:$(cat VERSION)

     # Deploy the Docker image to the GKE cluster
   - name: Deploy
     run: |
        gcloud run deploy ${{ secrets.GCLOUD_NAME }} --image gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_NAME }} --platform managed --region gcr.io
